.TH FURIGANAPAD "1" "June 2023" "furiganapad 0.6.0" "User Commands"
.SH NAME
\fBfuriganapad\fP \- text editor for Japanese texts with ruby characters
.SH DESCRIPTION
.B furiganapad
can be used to edit Japanese texts with ruby characters.
Ruby characters are automatically placed above Kanji characters when
converting Hiragana characters into Kanji characters by using
Hiragana IME for IBus.
.SS "Usage:"
.IP
furiganapad [OPTION?]
.SS "Help Options:"
.TP
\-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gapplication\fR
Show GApplication options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-x\fR, \fB\-\-window\-x\fR=\fI\,x\/\fR
Initial window x position
.TP
\fB\-y\fR, \fB\-\-window\-y\fR=\fI\,y\/\fR
Initial window y position
.TP
\fB\-w\fR, \fB\-\-window\-width\fR=\fI\,w\/\fR
Initial window width
.TP
\fB\-h\fR, \fB\-\-window\-height\fR=\fI\,h\/\fR
Initial window height
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-\-display\fR=\fI\,DISPLAY\/\fR
X display to use
