.TH FURIGANAPAD "1" "2023年6月" "furiganapad 0.6.0" "ユーザーコマンド"
.SH 名前
\fBfuriganapad\fP \- ふりがなつきの文章用のテキストエディター
.SH 説明
.B ふりがなパッド
は、ふりがなをうった文章をかんたんにつくれるテキスト エディターです。
ひらがなIMEとあわせてつかうと、漢字変換をしたときに漢字に自動的にふりがなをつけられます。
.SS "用法:"
.IP
furiganapad [オプション…]
.SS "ヘルプのオプション:"
.TP
\-?, \fB\-\-help\fR
ヘルプのオプションを表示する
.TP
\fB\-\-help\-all\fR
ヘルプのオプションをすべて表示する
.TP
\fB\-\-help\-gapplication\fR
GApplication のオプションを表示する
.TP
\fB\-\-help\-gtk\fR
GTK+ のオプションを表示する
.SS "アプリケーションのオプション:"
.TP
\fB\-x\fR, \fB\-\-window\-x\fR=\fI\,x\/\fR
ウインドウの x 座標
.TP
\fB\-y\fR, \fB\-\-window\-y\fR=\fI\,y\/\fR
ウインドウの y 座標
.TP
\fB\-w\fR, \fB\-\-window\-width\fR=\fI\,w\/\fR
ウインドウの幅
.TP
\fB\-h\fR, \fB\-\-window\-height\fR=\fI\,h\/\fR
ウインドウの高さ
.TP
\fB\-v\fR, \fB\-\-version\fR
バージョン番号を表示する
.TP
\fB\-\-display\fR=\fI\,DISPLAY\/\fR
使用する X のディスプレイを指定する
